// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWtAWMom51nJ_v5G0uGgStYTA4mwpo5oA',
    appId: '1:744866468853:web:6f4b9d30774940b57d06bc',
    messagingSenderId: '744866468853',
    projectId: 'farmer-s-buddy-19512',
    authDomain: 'farmer-s-buddy-19512.firebaseapp.com',
    storageBucket: 'farmer-s-buddy-19512.firebasestorage.app',
    measurementId: 'G-2Y9BZ9JG8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS4s0G9Vc1VQ2u646VHO95F42EZt2QQtE',
    appId: '1:744866468853:android:67e93e7083378bff7d06bc',
    messagingSenderId: '744866468853',
    projectId: 'farmer-s-buddy-19512',
    storageBucket: 'farmer-s-buddy-19512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGxg1-dyPRj2JFazaQsB6B600VnZngi2Q',
    appId: '1:744866468853:ios:f40df4cc200d328e7d06bc',
    messagingSenderId: '744866468853',
    projectId: 'farmer-s-buddy-19512',
    storageBucket: 'farmer-s-buddy-19512.firebasestorage.app',
    iosBundleId: 'com.example.growBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGxg1-dyPRj2JFazaQsB6B600VnZngi2Q',
    appId: '1:744866468853:ios:f40df4cc200d328e7d06bc',
    messagingSenderId: '744866468853',
    projectId: 'farmer-s-buddy-19512',
    storageBucket: 'farmer-s-buddy-19512.firebasestorage.app',
    iosBundleId: 'com.example.growBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWtAWMom51nJ_v5G0uGgStYTA4mwpo5oA',
    appId: '1:744866468853:web:ffc8b8e42a8e10ba7d06bc',
    messagingSenderId: '744866468853',
    projectId: 'farmer-s-buddy-19512',
    authDomain: 'farmer-s-buddy-19512.firebaseapp.com',
    storageBucket: 'farmer-s-buddy-19512.firebasestorage.app',
    measurementId: 'G-5GYWYNPEQ7',
  );

}